title: 'Test PUMRP PartsUnlimitedMRP'
subtitle: 'DevOps Hands On Labs'

# if you wish to integrate disqus on pages set your shortname here
disqus_shortname: ''

# if you use google analytics, add your tracking id here
google_analytics_id: ''

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 2

# URL to source code, used in _includes/footer.html
codeurl: 'https://github.com/eamonnk/TestPUMRP'

# Default categories (in order) to appear in the navigation
sections: [
    ['PracticesandPrinciples', 'DevOps Practices and Principles'],
    ['IaC', 'Infrastructure as Code'],
    ['CICD', 'Continuous Integration and Continuous Deployment'],
    ['ConfigMgmt', 'Configuration Mgmt For Containerized Delivery'],
    ['Testing', 'DevOps Testing'],
    ['Databases', ' DevOps with Databases'],
    ['App Monitoring', 'Application Monitoring and Feedback Loops'],
    ['Mobile', 'DevOps for Mobile Apps'],
    ['ArchDistriApps', 'Architecting Distributed Cloud Apps'],
    ['DevopsMPPCapstone', 'DevOps MPP Capstone Project'],
    ['AzureStack', 'Fundamentals on Azure Stack'],

]

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: '/TestPUMRP'

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
highlighter: rouge

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md']

# Use the kramdown Markdown renderer
markdown: kramdown
redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]
